version: "3"
services:

  app:
    container_name: zerf_interview
    tty: true
    build: 
      context: ./
      dockerfile: .docker/node/Dockerfile
      args:
        UID: 1000
        GID: 1000
    volumes:
      - "./src:/var/www/html"
    ports:
    - "3000:3000"
    - "9229:9229" #debug port 
    